import * as THREE from 'three';
import * as C from '../sim/constants';
import { bowlHeight, pocketAngles } from '../sim/physics';
import type { Theme } from './theme';
import { dishMaterial, noOutline, toonMaterial } from './toon';

/**
 * Handles onto every themed material in the stadium.
 *
 * Returned so a theme switch can re-parameterise in place. Rebuilding the
 * stadium on every switch would mean disposing geometries and materials by
 * hand, and one missed dispose is a GPU leak that only shows up after a dozen
 * toggles — assigning to existing materials avoids the whole class of bug.
 */
export interface StadiumHandles {
  group: THREE.Group;
  floor: THREE.MeshStandardMaterial;
  ridge: THREE.MeshBasicMaterial;
  guides: THREE.MeshBasicMaterial[];
  wall: THREE.MeshStandardMaterial;
  posts: THREE.MeshStandardMaterial[];
  skirt: THREE.MeshStandardMaterial;
}

/** Push a theme's values onto an already-built stadium. */
export function applyStadiumTheme(h: StadiumHandles, t: Theme): void {
  // Under toon the dish colour lives in its painted texture and the material
  // tint is left at white; re-applying the hex here would multiply the colour
  // into itself and the dish would come out near-black.
  if (!t.toon) {
    h.floor.color.setHex(t.dishColour);
    h.floor.metalness = t.dishMetalness;
    h.floor.roughness = t.dishRoughness;
  }

  h.ridge.color.setHex(t.ridgeColour);
  h.ridge.opacity = t.ridgeOpacity;

  for (const g of h.guides) {
    g.color.setHex(t.guideColour);
    g.opacity = t.guideOpacity;
  }

  h.wall.color.setHex(t.wallColour);
  h.wall.metalness = t.wallMetalness;
  h.wall.roughness = t.wallRoughness;

  for (const p of h.posts) {
    p.color.setHex(t.postColour);
    p.emissive.setHex(t.postColour);
    p.emissiveIntensity = t.postEmissive;
  }

  h.skirt.color.setHex(t.skirtColour);
}

/**
 * The stadium. The dish surface is generated by revolving the *same*
 * `bowlHeight` profile the physics uses, so what the player sees is exactly the
 * surface the tops are being pushed around on — including the tornado ridge.
 */
export function buildStadium(theme: Theme): StadiumHandles {
  const group = new THREE.Group();
  const guides: THREE.MeshBasicMaterial[] = [];
  const posts: THREE.MeshStandardMaterial[] = [];

  // ---- dish floor ----------------------------------------------------------
  const profile: THREE.Vector2[] = [];
  const steps = 96;
  for (let i = 0; i <= steps; i++) {
    const r = (i / steps) * C.STADIUM_RADIUS;
    profile.push(new THREE.Vector2(Math.max(r, 0.0001), bowlHeight(r)));
  }

  // The dish is rebuilt on a toon switch rather than re-parameterised, because
  // MeshToonMaterial is a different material class — the one place the
  // "assign, never rebuild" rule genuinely can't hold.
  const floorMat = (
    theme.toon
      ? // Unlit and painted — see `dishMaterial` for why this one surface
        // opts out of lighting entirely.
        dishMaterial(theme.dishColour)
      : new THREE.MeshStandardMaterial({
          color: theme.dishColour,
          metalness: theme.dishMetalness,
          roughness: theme.dishRoughness,
          side: THREE.DoubleSide,
        })
  ) as THREE.MeshStandardMaterial;
  floorMat.side = THREE.DoubleSide;
  // The dish is concave, so an inverted-hull outline lifts off it and paints the
  // basin dark — see `noOutline`. The rim, ridge and posts carry the linework.
  noOutline(floorMat);
  const floor = new THREE.Mesh(new THREE.LatheGeometry(profile, 128), floorMat);
  // An unlit dish can't take a shadow map; under toon the tops draw their own
  // contact shadow instead.
  floor.receiveShadow = !theme.toon;
  group.add(floor);

  // Concentric guide rings, so motion across the dish is readable.
  let ridgeMat: THREE.MeshBasicMaterial | null = null;
  for (const r of [0.25, 0.5, C.RIDGE_RADIUS]) {
    const isRidge = r === C.RIDGE_RADIUS;
    const mat = new THREE.MeshBasicMaterial({
      color: isRidge ? theme.ridgeColour : theme.guideColour,
      transparent: true,
      opacity: isRidge ? theme.ridgeOpacity : theme.guideOpacity,
    });
    if (isRidge) ridgeMat = mat;
    else guides.push(mat);
    const ring = new THREE.Mesh(new THREE.TorusGeometry(r, 0.004, 6, 128), mat);
    ring.rotation.x = Math.PI / 2;
    ring.position.y = bowlHeight(r) + 0.004;
    group.add(ring);
  }

  // ---- rim wall, with a gap at every exit pocket ---------------------------
  const rimHeight = 0.13;
  const rimY = bowlHeight(C.STADIUM_RADIUS) + rimHeight / 2;
  const pockets = pocketAngles().sort((a, b) => a - b);
  const wallMat = (
    theme.toon
      ? toonMaterial(theme.wallColour)
      : new THREE.MeshStandardMaterial({
          color: theme.wallColour,
          metalness: theme.wallMetalness,
          roughness: theme.wallRoughness,
          side: THREE.DoubleSide,
        })
  ) as THREE.MeshStandardMaterial;
  wallMat.side = THREE.DoubleSide;

  for (let i = 0; i < pockets.length; i++) {
    const start = pockets[i] + C.POCKET_HALF_WIDTH;
    const end = pockets[(i + 1) % pockets.length] - C.POCKET_HALF_WIDTH;
    let sweep = end - start;
    while (sweep <= 0) sweep += Math.PI * 2;

    const wall = new THREE.Mesh(
      new THREE.CylinderGeometry(
        C.STADIUM_RADIUS,
        C.STADIUM_RADIUS,
        rimHeight,
        64,
        1,
        true,
        0,
        sweep,
      ),
      wallMat,
    );
    // CylinderGeometry lays its vertices out as (sin t, cos t), so its sweep
    // starts at +Z and runs clockwise, while sim bearings are (cos a, sin a)
    // starting at +X. Rotating by -start leaves the segments in the wrong place
    // entirely; this is the offset that lines a segment's end up with `start`.
    wall.rotation.y = Math.PI / 2 - start - sweep;
    wall.position.y = rimY;
    group.add(wall);
  }

  // Glowing markers either side of each pocket, so exits are obvious.
  for (const angle of pockets) {
    for (const side of [-1, 1]) {
      const a = angle + side * C.POCKET_HALF_WIDTH;
      const postMat = (
        theme.toon
          ? toonMaterial(theme.postColour, theme.postEmissive * 0.4)
          : new THREE.MeshStandardMaterial({
              color: theme.postColour,
              emissive: theme.postColour,
              emissiveIntensity: theme.postEmissive,
            })
      ) as THREE.MeshStandardMaterial;
      posts.push(postMat);
      const post = new THREE.Mesh(
        new THREE.CylinderGeometry(0.012, 0.012, rimHeight * 1.5, 8),
        postMat,
      );
      post.position.set(
        Math.cos(a) * C.STADIUM_RADIUS,
        rimY,
        Math.sin(a) * C.STADIUM_RADIUS,
      );
      group.add(post);
    }
  }

  // ---- outer housing -------------------------------------------------------
  const skirtMat = new THREE.MeshStandardMaterial({
    color: theme.skirtColour,
    metalness: 0.4,
    roughness: 0.8,
  });
  const skirt = new THREE.Mesh(
    new THREE.CylinderGeometry(C.STADIUM_RADIUS * 1.32, C.STADIUM_RADIUS * 1.5, 0.16, 64),
    skirtMat,
  );
  // Sunk until its top cap clears the bowl.
  //
  // CylinderGeometry is capped, so this housing carries a solid disc of radius
  // 1.32 across its top. At the old y the cap sat at +0.06 while the dish floor
  // — bowlHeight(r) = 0.2r² — is below 0.06 for every r < 0.548. The cap was
  // therefore drawn *over the middle of the stadium*, and had been all along:
  // in the dark themes the skirt and dish colours were close enough that
  // nobody could see it, and on a bright painted dish it read as a black hole
  // exactly where the fight happens. Now the cap sits under the lowest point
  // of the bowl and can never win the depth test against the floor.
  skirt.position.y = -0.14;
  skirt.receiveShadow = true;
  group.add(skirt);

  return {
    group,
    floor: floorMat,
    ridge: ridgeMat as THREE.MeshBasicMaterial,
    guides,
    wall: wallMat,
    posts,
    skirt: skirtMat,
  };
}

/** World-space position for a top at sim coordinates (x, y). */
export function beyWorldPosition(x: number, y: number): THREE.Vector3 {
  const r = Math.hypot(x, y);
  return new THREE.Vector3(x, bowlHeight(Math.min(r, C.STADIUM_RADIUS)), y);
}
