import * as THREE from 'three';
import * as C from '../sim/constants';
import { bowlHeight, pocketAngles } from '../sim/physics';

/**
 * The stadium. The dish surface is generated by revolving the *same*
 * `bowlHeight` profile the physics uses, so what the player sees is exactly the
 * surface the tops are being pushed around on — including the tornado ridge.
 */
export function buildStadium(): THREE.Group {
  const group = new THREE.Group();

  // ---- dish floor ----------------------------------------------------------
  const profile: THREE.Vector2[] = [];
  const steps = 96;
  for (let i = 0; i <= steps; i++) {
    const r = (i / steps) * C.STADIUM_RADIUS;
    profile.push(new THREE.Vector2(Math.max(r, 0.0001), bowlHeight(r)));
  }

  const floor = new THREE.Mesh(
    new THREE.LatheGeometry(profile, 128),
    new THREE.MeshStandardMaterial({
      color: 0x232c3d,
      metalness: 0.3,
      roughness: 0.66,
      side: THREE.DoubleSide,
    }),
  );
  floor.receiveShadow = true;
  group.add(floor);

  // Concentric guide rings, so motion across the dish is readable.
  for (const r of [0.25, 0.5, C.RIDGE_RADIUS]) {
    const ring = new THREE.Mesh(
      new THREE.TorusGeometry(r, 0.004, 6, 128),
      new THREE.MeshBasicMaterial({
        color: r === C.RIDGE_RADIUS ? 0x38bdf8 : 0x2b3648,
        transparent: true,
        opacity: r === C.RIDGE_RADIUS ? 0.55 : 0.35,
      }),
    );
    ring.rotation.x = Math.PI / 2;
    ring.position.y = bowlHeight(r) + 0.004;
    group.add(ring);
  }

  // ---- rim wall, with a gap at every exit pocket ---------------------------
  const rimHeight = 0.13;
  const rimY = bowlHeight(C.STADIUM_RADIUS) + rimHeight / 2;
  const pockets = pocketAngles().sort((a, b) => a - b);
  const wallMat = new THREE.MeshStandardMaterial({
    color: 0x2f3a4d,
    metalness: 0.5,
    roughness: 0.5,
    side: THREE.DoubleSide,
  });

  for (let i = 0; i < pockets.length; i++) {
    const start = pockets[i] + C.POCKET_HALF_WIDTH;
    const end = pockets[(i + 1) % pockets.length] - C.POCKET_HALF_WIDTH;
    let sweep = end - start;
    while (sweep <= 0) sweep += Math.PI * 2;

    const wall = new THREE.Mesh(
      new THREE.CylinderGeometry(
        C.STADIUM_RADIUS,
        C.STADIUM_RADIUS,
        rimHeight,
        64,
        1,
        true,
        0,
        sweep,
      ),
      wallMat,
    );
    // CylinderGeometry lays its vertices out as (sin t, cos t), so its sweep
    // starts at +Z and runs clockwise, while sim bearings are (cos a, sin a)
    // starting at +X. Rotating by -start leaves the segments in the wrong place
    // entirely; this is the offset that lines a segment's end up with `start`.
    wall.rotation.y = Math.PI / 2 - start - sweep;
    wall.position.y = rimY;
    group.add(wall);
  }

  // Glowing markers either side of each pocket, so exits are obvious.
  for (const angle of pockets) {
    for (const side of [-1, 1]) {
      const a = angle + side * C.POCKET_HALF_WIDTH;
      const post = new THREE.Mesh(
        new THREE.CylinderGeometry(0.012, 0.012, rimHeight * 1.5, 8),
        new THREE.MeshStandardMaterial({
          color: 0xf97316,
          emissive: 0xf97316,
          emissiveIntensity: 0.9,
        }),
      );
      post.position.set(
        Math.cos(a) * C.STADIUM_RADIUS,
        rimY,
        Math.sin(a) * C.STADIUM_RADIUS,
      );
      group.add(post);
    }
  }

  // ---- outer housing -------------------------------------------------------
  const skirt = new THREE.Mesh(
    new THREE.CylinderGeometry(C.STADIUM_RADIUS * 1.32, C.STADIUM_RADIUS * 1.5, 0.16, 64),
    new THREE.MeshStandardMaterial({ color: 0x121722, metalness: 0.4, roughness: 0.8 }),
  );
  skirt.position.y = -0.02;
  skirt.receiveShadow = true;
  group.add(skirt);

  return group;
}

/** World-space position for a top at sim coordinates (x, y). */
export function beyWorldPosition(x: number, y: number): THREE.Vector3 {
  const r = Math.hypot(x, y);
  return new THREE.Vector3(x, bowlHeight(Math.min(r, C.STADIUM_RADIUS)), y);
}
